// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const bulkUpdateEvents = `-- name: BulkUpdateEvents :batchexec
UPDATE events
SET 
    title = $2, 
    card_title = $3, 
    card_subtitle = $4, 
    card_detailed_text = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type BulkUpdateEventsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BulkUpdateEventsParams struct {
	ID               pgtype.UUID `json:"id"`
	Title            string      `json:"title"`
	CardTitle        string      `json:"card_title"`
	CardSubtitle     pgtype.Text `json:"card_subtitle"`
	CardDetailedText pgtype.Text `json:"card_detailed_text"`
}

func (q *Queries) BulkUpdateEvents(ctx context.Context, arg []BulkUpdateEventsParams) *BulkUpdateEventsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Title,
			a.CardTitle,
			a.CardSubtitle,
			a.CardDetailedText,
		}
		batch.Queue(bulkUpdateEvents, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BulkUpdateEventsBatchResults{br, len(arg), false}
}

func (b *BulkUpdateEventsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BulkUpdateEventsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
