// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkCreateEvents implements pgx.CopyFromSource.
type iteratorForBulkCreateEvents struct {
	rows                 []BulkCreateEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TimelineID,
		r.rows[0].Title,
		r.rows[0].CardTitle,
		r.rows[0].CardSubtitle,
		r.rows[0].CardDetailedText,
	}, nil
}

func (r iteratorForBulkCreateEvents) Err() error {
	return nil
}

func (q *Queries) BulkCreateEvents(ctx context.Context, arg []BulkCreateEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"events"}, []string{"timeline_id", "title", "card_title", "card_subtitle", "card_detailed_text"}, &iteratorForBulkCreateEvents{rows: arg})
}
