// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateEventsParams struct {
	TimelineID       pgtype.UUID `json:"timeline_id"`
	Title            string      `json:"title"`
	CardTitle        string      `json:"card_title"`
	CardSubtitle     pgtype.Text `json:"card_subtitle"`
	CardDetailedText pgtype.Text `json:"card_detailed_text"`
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEventsByTimelineId = `-- name: GetEventsByTimelineId :many
SELECT id, timeline_id, title, card_title, card_subtitle, card_detailed_text, created_at, updated_at FROM events
WHERE timeline_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetEventsByTimelineId(ctx context.Context, timelineID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByTimelineId, timelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TimelineID,
			&i.Title,
			&i.CardTitle,
			&i.CardSubtitle,
			&i.CardDetailedText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
