// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timelines.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimeline = `-- name: CreateTimeline :one
INSERT INTO TIMELINES (user_id, title, description)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, description, created_at
`

type CreateTimelineParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

type CreateTimelineRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTimeline(ctx context.Context, arg CreateTimelineParams) (CreateTimelineRow, error) {
	row := q.db.QueryRow(ctx, createTimeline, arg.UserID, arg.Title, arg.Description)
	var i CreateTimelineRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTimeline = `-- name: DeleteTimeline :exec
DELETE FROM timelines
WHERE id = $1
`

func (q *Queries) DeleteTimeline(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimeline, id)
	return err
}

const getTimeLineById = `-- name: GetTimeLineById :one
SELECT id, user_id, title, description, created_at, updated_at FROM timelines
WHERE id = $1
`

func (q *Queries) GetTimeLineById(ctx context.Context, id pgtype.UUID) (Timeline, error) {
	row := q.db.QueryRow(ctx, getTimeLineById, id)
	var i Timeline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTimelinesByUserId = `-- name: GetTimelinesByUserId :many
SELECT id, user_id, title, description, created_at, updated_at FROM timelines
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTimelinesByUserId(ctx context.Context, userID pgtype.UUID) ([]Timeline, error) {
	rows, err := q.db.Query(ctx, getTimelinesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Timeline
	for rows.Next() {
		var i Timeline
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimelinesByUserIdAndTitle = `-- name: GetTimelinesByUserIdAndTitle :many
SELECT id, user_id, title, description, created_at, updated_at FROM timelines
WHERE user_id = $1 AND title ILIKE '%' || $2 || '%'
ORDER BY created_at DESC
`

type GetTimelinesByUserIdAndTitleParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

func (q *Queries) GetTimelinesByUserIdAndTitle(ctx context.Context, arg GetTimelinesByUserIdAndTitleParams) ([]Timeline, error) {
	rows, err := q.db.Query(ctx, getTimelinesByUserIdAndTitle, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Timeline
	for rows.Next() {
		var i Timeline
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeline = `-- name: UpdateTimeline :one
UPDATE timelines
SET title = $2, description = $3
WHERE id = $1
RETURNING id, user_id, title, description
`

type UpdateTimelineParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

type UpdateTimelineRow struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateTimeline(ctx context.Context, arg UpdateTimelineParams) (UpdateTimelineRow, error) {
	row := q.db.QueryRow(ctx, updateTimeline, arg.ID, arg.Title, arg.Description)
	var i UpdateTimelineRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
	)
	return i, err
}
