// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const bulkUpdateEvents = `-- name: BulkUpdateEvents :batchexec
UPDATE events e
SET 
    time_marker = $3,
    title = $4,
    subtitle = $5,
    description = $6,
    media_name = $7,
    media_type = $8,
    media_url = $9,
    updated_at = CURRENT_TIMESTAMP
FROM timelines t
WHERE e.id = $1
  AND e.timeline_id = t.id
  AND t.user_id = $2
`

type BulkUpdateEventsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BulkUpdateEventsParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	TimeMarker  string      `json:"time_marker"`
	Title       string      `json:"title"`
	Subtitle    pgtype.Text `json:"subtitle"`
	Description pgtype.Text `json:"description"`
	MediaName   pgtype.Text `json:"media_name"`
	MediaType   pgtype.Text `json:"media_type"`
	MediaUrl    pgtype.Text `json:"media_url"`
}

func (q *Queries) BulkUpdateEvents(ctx context.Context, arg []BulkUpdateEventsParams) *BulkUpdateEventsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.UserID,
			a.TimeMarker,
			a.Title,
			a.Subtitle,
			a.Description,
			a.MediaName,
			a.MediaType,
			a.MediaUrl,
		}
		batch.Queue(bulkUpdateEvents, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BulkUpdateEventsBatchResults{br, len(arg), false}
}

func (b *BulkUpdateEventsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BulkUpdateEventsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
