// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookmarks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBookmark = `-- name: AddBookmark :exec
INSERT INTO bookmarks (user_id, timeline_id)
VALUES ($1, $2)
`

type AddBookmarkParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	TimelineID pgtype.UUID `json:"timeline_id"`
}

func (q *Queries) AddBookmark(ctx context.Context, arg AddBookmarkParams) error {
	_, err := q.db.Exec(ctx, addBookmark, arg.UserID, arg.TimelineID)
	return err
}

const getBookmarkedTimelinesByUserId = `-- name: GetBookmarkedTimelinesByUserId :many
SELECT
    t.id,
    t.user_id,
    t.title,
    t.description,
    t.is_public,
    t.created_at
FROM bookmarks b
JOIN timelines t ON t.id = b.timeline_id
WHERE b.user_id = $1 AND (t.is_public = true OR t.user_id = $1)
ORDER BY t.created_at DESC
`

type GetBookmarkedTimelinesByUserIdRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	IsPublic    pgtype.Bool        `json:"is_public"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetBookmarkedTimelinesByUserId(ctx context.Context, userID pgtype.UUID) ([]GetBookmarkedTimelinesByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getBookmarkedTimelinesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookmarkedTimelinesByUserIdRow
	for rows.Next() {
		var i GetBookmarkedTimelinesByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBookmark = `-- name: RemoveBookmark :exec
DELETE FROM bookmarks
WHERE user_id = $1 AND timeline_id = $2
`

type RemoveBookmarkParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	TimelineID pgtype.UUID `json:"timeline_id"`
}

func (q *Queries) RemoveBookmark(ctx context.Context, arg RemoveBookmarkParams) error {
	_, err := q.db.Exec(ctx, removeBookmark, arg.UserID, arg.TimelineID)
	return err
}
