// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	UserID     pgtype.UUID `json:"user_id"`
	TimelineID pgtype.UUID `json:"timeline_id"`
}

type Event struct {
	ID          pgtype.UUID        `json:"id"`
	TimelineID  pgtype.UUID        `json:"timeline_id"`
	TimeMarker  string             `json:"time_marker"`
	Title       string             `json:"title"`
	Subtitle    pgtype.Text        `json:"subtitle"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	MediaName   pgtype.Text        `json:"media_name"`
	MediaType   pgtype.Text        `json:"media_type"`
	MediaUrl    pgtype.Text        `json:"media_url"`
	Position    pgtype.Int4        `json:"position"`
}

type Timeline struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsPublic    pgtype.Bool        `json:"is_public"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
